source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Super-NFT/Go23Spec.git'

use_frameworks!

platform :ios, '10.0'

target 'Go23LiteSDK_Example' do
  pod 'Go23LiteSDK', :path => '../'

  target 'Go23LiteSDK_Tests' do
    inherit! :search_paths

    
  end
end
